version: "3"

services:
# ahora se indican los servicios por el orden en que se quiere que se inicien.
#Por ejemplo, mongo debe estar antes de order.
#mongo: mismo nombre usado en el run.sh de Order y application.properties. #Se resuelve en una dirección IP.

  mongo:
    image: pauromers/p2gps:db
    deploy:
      replicas: 1 # para escabilidad del servicio.
      resources:
        limits:
          cpus: "0.15"
          #memory: 200M
      restart_policy:
        condition: none #reinicar el contenedor si falla
    ports:
      - "28017" # mapeo el Puerto del contenedor (derecha) con el puerto del host del servicio
      - "27017"
    volumes:
      - "db-data:/var/logs/" # para dar persistencia a la sesión
  order:
    image: pauromers/p2gps:order
    depends_on:
      - "mongo" #le pasamos al servicio order la IP del servicio mongo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          #memory: 500M
      restart_policy:
        condition: none
    ports:
      - "8082"
  web:
    image: pauromers/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          #memory: 300M
      restart_policy:
        condition: none
    ports:
      - "8082"
volumes:
  db-data:
    driver: azure_file
    driver_opts:
      share_name: db-data
      storage_account_name: almacengps98775